'''
This script get the files generated by "system_measurement_procedure.py"
data and extract the external field strenght throught the peak of the 
second harmonic of the excitation field in the fluxgate sensor.

@author: Tarcis Becher
'''

# import libraries
from scipy.fftpack import fft
import numpy as np
import csv, matplotlib.pyplot as plt


# User information
filePrefix = 'FLUXGT'

# Of the files
firstIndex = 3
lastIndex = 131

# Real sampling time (The user must know it)
Ts = 1.84e-6

# Frequency used to excitate the fluxgate coil
Fex = 100000


#%% Get the data from csv files
voltData = list()
pi = np.pi
nFiles = lastIndex - firstIndex

for i in range(0,nFiles): 
    file = open(filePrefix + str(i+ firstIndex) + '.csv', 'r')        
    reader = csv.reader(file, delimiter=';', quoting=csv.QUOTE_NONE)
    index = 0
    voltData.append(list())
    
    for row in reader:
        if index > 1:
            voltData[i].append(float(row[0]))
        index += 1
        
#%% Calculation of fft

# Second harmonic for analysis
desiredFreq = Fex*2
BVvector = list()
fftData = list()

file = open('results.csv')

for j in range(0,nFiles):
    Fs = 1/Ts
    #print(Fs)
    Fmax = Fs/2
    N = len(voltData[j]) 
    minS = round(N*(desiredFreq*0.95/Fs))
    maxS = round(N*(desiredFreq*1.00/Fs))+1
    
    xTime = np.linspace(0.0, N*Ts, N)
    fftData.append(fft(voltData[j]))
    xFreq = np.linspace(0.0, Fmax, N//2)
    BVvector.append(max( 2.0/N * np.abs(fftData[j][minS:maxS] )))
    
    if j < 0:
        BVvector[j] = -BVvector[j]
    '''
    fig = plt.figure(figsize=(10,10), dpi=50)
    plt.plot(xFreq, 2.0/N * np.abs(fftData[j][0:N//2]))
    plt.grid()
    plt.show()
    '''
    file.write(str(BVvector[j]))
    file.write(";\n")

file.close()
    
fig = plt.figure(figsize=(10,10), dpi=50)
plt.scatter(range(0,len(BVvector)), BVvector)


plt.show()
